// Replacement ViewBillModal.jsx generated by ChatGPT
// Copy this file into src/components/bills/ViewBillModal.jsx

import { useEffect, useState } from "react";
import api from "../../services/api";
import toast from "react-hot-toast";

function ViewBillModal({ isOpen, onClose, selectedBill, refreshBills }) {
  const [bill, setBill] = useState(null);
  const [loading, setLoading] = useState(false);
  const [processingPayment, setProcessingPayment] = useState(false);

  useEffect(() => {
    if (isOpen && selectedBill) fetchBill();
  }, [isOpen, selectedBill]);

  const fetchBill = async () => {
    try {
      setLoading(true);
      const response = await api.get(`/manager/bill/${selectedBill.order_id}`);
      setBill(response.data);
    } catch {
      toast.error("Failed to load bill.");
    } finally {
      setLoading(false);
    }
  };

  const handlePrintBill = () => window.print();

  const handleReceivePayment = async () => {
    try {
      setProcessingPayment(true);
      const response = await api.put(`/manager/orders/${bill.order_id}/status`, { status: "Completed" });
      toast.success(response.data.message);
      await fetchBill();
      await refreshBills();
      onClose();
    } catch (error) {
      toast.error(error.response?.data?.detail || "Payment failed.");
    } finally {
      setProcessingPayment(false);
    }
  };

  if (!isOpen || !selectedBill) return null;

  return (
    <div className="fixed inset-0 bg-black/50 flex justify-center items-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-5xl max-h-[90vh] flex flex-col">
        <div className="flex justify-between items-center border-b px-8 py-6">
          <div>
            <h2 className="text-3xl font-bold text-blue-700">Restaurant Bill</h2>
            <p className="text-gray-500">Review payment before completing the order</p>
          </div>
          <button onClick={onClose} className="text-3xl text-gray-400 hover:text-black">×</button>
        </div>

        <div className="flex-1 overflow-y-auto p-8">
          {loading ? (
            <div className="text-center py-20">Loading Bill...</div>
          ) : bill && (
            <>
              <div className="text-center border-b pb-6 mb-8">
                <h1 className="text-4xl font-bold">{bill.restaurant_name}</h1>
                <p className="text-gray-500 mt-2">Restaurant Billing Receipt</p>
                <p className="text-gray-400 text-sm">Thank you for dining with us</p>
              </div>

              <div className="grid grid-cols-2 md:grid-cols-3 gap-6 mb-8">
                <div className="bg-gray-50 rounded-xl p-5"><p className="text-sm text-gray-500">Table Number</p><h3 className="text-2xl font-bold">{bill.table_number}</h3></div>
                <div className="bg-gray-50 rounded-xl p-5"><p className="text-sm text-gray-500">Order Status</p><h3 className="text-2xl font-bold text-blue-600">{bill.status}</h3></div>
                <div className="bg-gray-50 rounded-xl p-5"><p className="text-sm text-gray-500">Payment</p><h3 className={`text-2xl font-bold ${bill.payment_status==="Paid"?"text-green-600":"text-red-600"}`}>{bill.payment_status}</h3></div>
                <div className="bg-gray-50 rounded-xl p-5"><p className="text-sm text-gray-500">Order Date</p><h3>{new Date(bill.ordered_at).toLocaleString()}</h3></div>
                <div className="bg-gray-50 rounded-xl p-5"><p className="text-sm text-gray-500">Bill Requested</p><h3>{bill.bill_requested_at?new Date(bill.bill_requested_at).toLocaleString():"-"}</h3></div>
              </div>

              <table className="w-full border rounded-xl overflow-hidden">
                <thead className="bg-blue-600 text-white">
                  <tr><th className="p-4 text-left">Item</th><th className="p-4 text-center">Qty</th><th className="p-4 text-center">Unit Price</th><th className="p-4 text-center">Subtotal</th></tr>
                </thead>
                <tbody>
                  {bill.items.map((item,index)=>(
                    <tr key={index} className="border-t hover:bg-gray-50">
                      <td className="p-4">{item.item_name}</td>
                      <td className="p-4 text-center">{item.quantity}</td>
                      <td className="p-4 text-center">Rs. {item.unit_price}</td>
                      <td className="p-4 text-center font-bold">Rs. {item.subtotal}</td>
                    </tr>
                  ))}
                </tbody>
              </table>

              <div className="mt-8 flex justify-end">
                <div className="w-80 bg-blue-50 border border-blue-200 rounded-xl p-6">
                  <div className="flex justify-between"><span>Total Items</span><span>{bill.items.length}</span></div>
                  <hr className="my-3"/>
                  <div className="flex justify-between text-2xl font-bold text-blue-700"><span>Total</span><span>Rs. {bill.total_amount}</span></div>
                </div>
              </div>
            </>
          )}
        </div>

        <div className="border-t px-8 py-5 flex justify-end gap-3">
          <button onClick={onClose} className="px-6 py-3 rounded-lg bg-gray-300">Close</button>
          <button onClick={handlePrintBill} className="px-6 py-3 rounded-lg bg-blue-600 text-white">Print Bill</button>
          {bill?.payment_status!=="Paid"&&(
            <button onClick={handleReceivePayment} disabled={processingPayment} className="px-6 py-3 rounded-lg bg-green-600 text-white">
              {processingPayment?"Processing...":"Receive Payment"}
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

export default ViewBillModal;
